@startuml

scale max 1920 width
left to right direction

skinparam nodesep 18
skinparam ranksep 37
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Tahoma
skinparam defaultFontSize 12
skinparam roundCorner 6
skinparam dpi 150
skinparam arrowColor black
skinparam arrowThickness 0.5
skinparam packageTitleAlignment left

' oval
skinparam usecase {
  borderThickness 0.5
}

' rectangle
skinparam rectangle {
  borderThickness 0.5
}

' component
skinparam component {
  borderThickness 1
}


package "Index" {
  (<b>index</b>)
}

package "App" {
  (app)
}

package "Routes" {
  (category.route)
  (product.route)
  (productPromotion.route)
  (shop.route)
  (user.route)
}


package "Controllers" {
  (category.controller)
  (error.controller)
  (product.controller)
  (productPromotion.controller)
  (shop.controller)
  (user.controller)
}

package "Models" {
  (category.model)
  (product.model)
  (productPromotion.model)
  (shop.model)
  (user.model)
}


package "Middlewares" {
  (authorization.middleware)
}



package "Services" {
    (scrapper.service)
    (error.service)
}

(app) --> (authorization.middleware)
(app) ------> (error.service)
(app) --> (category.route)
(app) --> (error.controller)
(app) --> (product.route)
(app) --> (productPromotion.route)
(app) --> (shop.route)
(app) --> (user.route)
(authorization.middleware) ---> (user.model)
(category.controller) ---> (category.model)
(category.route) --> (category.controller)
(<b>index</b>) -[thickness=1]> (app)
(product.controller) ---> (category.model)
(product.controller) ---> (product.model)
(product.controller) ---> (shop.model)
(product.controller) ---> (user.model)
(product.controller) -----> (scrapper.service)
(product.route) --> (product.controller)
(productPromotion.controller) ---> (product.model)
(productPromotion.controller) ---> (productPromotion.model)
(productPromotion.controller)  -----> (scrapper.service)
(productPromotion.route) --> (productPromotion.controller)
(shop.controller) ---> (shop.model)
(shop.route) --> (shop.controller)
(user.controller) ---> (user.model)
(user.route) --> (authorization.middleware)
(user.route) --> (user.controller)

@enduml

' View and edit on https://arkit.pro